apiVersion: v1
kind: Service
metadata:
  name: my-example-svc
  labels:
    app: example
spec:
  type: NodePort
  ports:
  - name: example-port
    nodePort: 32000
    port: 9002
    targetPort: 9002
  selector:
    app: example

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-example
  labels:
    app: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example
        image: dhaval2010/docker-example
        env:
        - name: ALPHABET
          value: b
        - name: PORT
          value: "9002"
        ports:
        - containerPort: 9002
