apiVersion: v1
kind: Service
metadata:
  name: my-example-svc
  labels:
    app: example
spec:
  type: NodePort
  ports:
  - name: example-port
    nodePort: 32000
    port: 9002
    targetPort: 9002
  selector:
    app: example
